etcd-io/auger

.github/dependabot.yml
Let's reduce the future maintenance overhead for Auger by setting up weekly automated pr's for go and github actions dependencies via dependabot.
=> Add dependabot for actions and gomod

.github/workflows/static-analysis.yaml, cmd/decode.go, cmd/decode_test.go, cmd/extract.go, cmd/root.go, pkg/data/data.go, pkg/encoding/encoding.go, pkg/encoding/encoding_test.go, pkg/encoding/scheme.go
This pull request introduces a basic new github actions workflow for running `golangci-lint` so we can keep on top of this moving forward.
In a second commit I've also quickly gone through all the lint errors and made an initial rushed attempt at fixing them, @siyuanfoundation can you please take a close look at these.
=> Add new workflow for static analysis checks & address lint errors

.github/workflows/static-analysis.yaml, Makefile, cmd/analyze.go, cmd/checksum.go, cmd/decode.go, cmd/encode.go, cmd/extract.go, pkg/data/data.go, pkg/data/data_test.go, pkg/encoding/scheme.go, scripts/fix.sh, tools/.golangci.yaml
Add Makefile targets for running fmt and static analysis checks
Changes:
- Introduce `make verify` and `make fmt` targets in Makefile
- For linter, use the same config as etcd repo
- Update GitHubCI workflow accordingly 
Closes #31
References:
- [fmt and lint](https://github.com/etcd-io/bbolt/blob/c57b3537ed933f2e613f04d42688d49e511f69b3/Makefile#L30C1-L36C84) 
- [fmt script](https://github.com/etcd-io/etcd/blob/a08812eb01572aa64479543d1e8fa33cda22b8b8/scripts/fix.sh)
- [GithubCI](https://github.com/etcd-io/etcd/blob/a08812eb01572aa64479543d1e8fa33cda22b8b8/.github/workflows/static-analysis.yaml)
- [linter config](https://github.com/etcd-io/etcd/blob/a08812eb01572aa64479543d1e8fa33cda22b8b8/tools/.golangci.yaml)
=> Add make verify target for running static analysis checks

tools/.golangci.yaml
Tidy up the golangci config file according to the PR discussion in etcd repo
Reference:
- https://github.com/etcd-io/etcd/pull/17694#discussion_r1548334836
=> Move exclude-files to issues section

.github/workflows/static-analysis.yaml, .github/workflows/tests.yaml
after https://github.com/etcd-io/auger/pull/44, go version update to 1.22.0, this PR is working for update go version of ci
cc @siyuanfoundation
=> chore: update go version to use go.mod as go-version-file.

cmd/decode.go, cmd/encode.go, cmd/extract.go, pkg/data/data.go, pkg/encoding/encoding.go
Let its input and output types be the same
=> Refactor encoding.Convert

pkg/encoding/encoding.go
=> Public encoding.DecodeTypeMeta

pkg/encoding/encoding.go
> CRDs currently can be read with --output=json and that is generally how it is encoded in k8s as well. I think there are discussions regarding other encoders for CRDs. Until that changes, we do not really need to worry about that. However we do need to add better documentation of how to decode CRDs.
Since you mentioned in [#33 ](url) that CRDs can be read using `--output=json,` I believe this indicates that auger is functionally capable of correctly accessing data in the `application/json` format (similarly for other data types like CRDs which are also in `application/json` format). Therefore, I think that when attempting to read this data without the `--output=json` parameter, the output `error decoding from application/json: xxxx` is an unfriendly of program logic, because this data …
=> Explicitly convert inMediaType json to outMediaType yaml

Dockerfile, Makefile, go.mod
Keep auger in sync with rest of etcd project repositories.
=> Bump golang to latest patch release 1.22.4.

.github/dependabot.yml, .github/workflows/static-analysis.yaml, .github/workflows/tests.yaml, Dockerfile, Makefile, README.md, go.mod
Some quick maintenance while I had a moment spare today:
- **Update to latest go patch release 1.22.6.**
- **Pin github actions dependencies by commit sha.**
- **Bump golangci-lint version to align with etcd-io/etcd.**
- **Resolve markdownlint issues in README.md.**
=> Bump go & golangci-lint and pin actions dependencies

go.mod
The go directive from the `go.mod` file should be set to the minimum version required to compile packages from the module, and use `toolchain` to specify the latest go version [2].
This project's code should work fine with any version greater than 1.22. It will prevent projects that depend on this package from getting a go directive version bump every time there's a new version of this dependency.
Please see a similar issue we had during the etcd dependency update [1].
Reference:
[1] https://github.com/etcd-io/etcd/pull/18418#discussion_r1709929410 
[2] https://github.com/alexfalkowski/gocovmerge/pull/87
=> Move the go directive version to toolchain

.github/workflows/static-analysis.yaml, Dockerfile, Makefile, go.mod
Reference:
- https://github.com/etcd-io/etcd/issues/18443
=> Bump go toolchain to 1.23.0

Dockerfile
=> Revert "Bump golang from `d0b3155` to `613a108`"

Makefile
I got error:
`auger: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by auger)`
On my Ubuntu after building auger, adding CGO_ENABLED=0 to build env vars solved the problem. I'm not a Go expert but it did just solve my issue.
=> Added CGO_ENABLED=0 to build args

augerctl/command/get_command.go, augerctl/command/printer.go, augerctl/command/printer_json.go, augerctl/command/printer_yaml.go
part of https://github.com/etcd-io/auger/issues/3
=> [augerctl] Support for the json format as output

Makefile, go.mod
Reference:
- https://github.com/etcd-io/etcd/issues/18665
=> [main] Bump go toolchain to 1.23.2

.github/workflows/release.yaml, .gitignore, .goreleaser.yaml, RELEASE.md, augerctl/command/ctl.go, augerctl/command/version.go, cmd/version.go
closes #28
This will add a `goreleaser` based release process as described in the updated `RELEASE.md`
An example release with artifacts can be seen here: https://github.com/bavarianbidi/auger/releases/tag/v0.1.0
https://github.com/bavarianbidi/auger/actions/runs/11392186824/job/31697673348 will give you the github actions output of the release process, produced by `goreleaser`.
=> goreleaser based release build

pkg/data/data.go
Hi All,
Thank you for your dedicated work on this wonderful project. I was in the process of building something similar and was delighted to come across your existing efforts.
I wanted to address an issue I encountered while using auger with the -f extract option when specifying an etcd snapshot that does not exist.
As many of you may know, this utility uses the `bolt "go.etcd.io/bbolt"` library.
When opening files, it will automatically create a new file if it does not exist. This behaviour is depicted in the following example from the Bolt repository:
```
func main() {
// Open the my.db data file in your current directory.
// It will be created if it doesn't exist.
db, err := bolt.Open("my.db", 0600, nil)
if err != nil {
log.Fatal(err)
}
defer db.Close()
...
}
```
Although this …
=> check file exists before using bolt.Open

Dockerfile
This should fix depdendabot being able to suggest the correct new image for auger and resolve the issue we initially saw back in https://github.com/etcd-io/auger/pull/97#issuecomment-2299884674.
cc @ivanvc
=> Ensure desired golang image tag is specified

Makefile, README.md
closes #156 
```sh
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
make: *** [/go/src/github.com/etcd-io/auger/Makefile:67: release-docker-build] Error 1
make: *** [Makefile:55: release] Error 2
```
=> Remove defunct makefile recipes for release

.goreleaser.yaml
the build args contain a typo in the path to set the version, git commit sha and build time.
And therefore the version information is wrong:
```bash
auger version
Version:        v0.0.0-dev
BuildTime:      1970-01-01T00:00:00Z
GitCommit:
GoVersion:      go1.23.3
Compiler:       gc
OS/Arch:        linux/amd64
augerctl version
Version:        v0.0.0-dev
BuildTime:      1970-01-01T00:00:00Z
GitCommit:
GoVersion:      go1.23.3
Compiler:       gc
```
this PR fixes the issue and add correct version information (tested with a fake `v1.0.3` version on my fork):
```bash
auger version                                                                                                                             Version:        1.0.3
BuildTime:      2024-11-18T13:26:07Z
GitCommit: …
```
=> fix: correct the build args version injection

go.mod
Updated Go Version to 1.23.4
Part of https://github.com/etcd-io/etcd/issues/19000
=> Update Go Version to 1.23.4

go.mod
Updates auger golang toolchain from `1.23.4` to `1.23.5`
Subtask from Issue: https://github.com/etcd-io/etcd/issues/19210
Verified as:
```
make build
make test
```
=> Update auger golang toolchain to 1.23.5

go.mod
Updating golang toolchain to version 1.23.6
Subtask of https://github.com/etcd-io/etcd/issues/19333
Verified with
```
make build
make test
```
=> Update golang toolchain to version 1.23.6

.github/workflows/static-analysis.yaml
https://github.com/etcd-io/auger/pull/208 CI failure is due to linter version used is built using go1.23.
This PR bumps the go-linter version used in CI
@ivanvc @henrybear327
=> Bump go linter 1.24

.github/workflows/static-analysis.yaml
ref https://github.com/etcd-io/etcd/issues/19417
cc @ivanvc @henrybear327
=> bump golangci-lint v1.64.5

go.mod
ref https://github.com/etcd-io/etcd/issues/19417
=> Bump go 1.24.0

tools/.golangci.yaml
Fixes .golangci.yaml config (golangci-lint config verify passes) and sort fields.
=> chore: clean up golangci-lint

augerctl/command/global.go, cmd/analyze.go, cmd/checksum.go, cmd/decode.go, cmd/encode.go, cmd/extract.go, pkg/client/client_get.go, pkg/client/util.go, pkg/data/data.go, pkg/encoding/encoding.go, pkg/scheme/init.go, tools/.golangci.yaml
enable the following rules from revive :
* receiver-naming
* redundant-import-alias
* unnecessary-stmt
* unused-parameter
* use-any
* use-errors-new
* useless-break
=> chore: enable more rules from revive

augerctl/command/get_command.go, cmd/decode.go, cmd/extract.go, pkg/data/data.go, pkg/encoding/encoding.go, pkg/scheme/init.go, tools/.golangci.yaml
Align golangci-lint config with [etcd](https://github.com/etcd-io/etcd/blob/main/tools/.golangci.yaml)
=> chore: align golangci-lint config with etcd

go.mod
Updating golang toolchain to version 1.24.1
Subtask of https://github.com/etcd-io/etcd/issues/19524
Verified with
```
make build
make test`
=> Update golang toolchain to version 1.24.1

Dockerfile, go.mod
Reference https://github.com/etcd-io/etcd/issues/19713
=> Bump go toolchain to v1.24.2
